"""card_table migration

Revision ID: 43b58a8197ad
Revises: f348de7f1c84
Create Date: 2023-05-14 11:01:08.888489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b58a8197ad'
down_revision = 'f348de7f1c84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
